name: Do a Duolingo lesson Diego

on:
  workflow_dispatch:
    inputs:
      lessons:
        default: 1
        description: 'Number of lessons to be completed'
        required: false
        type: number

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node index.js
        env:
          DUOLINGO_JWT: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjYzMDcyMDAwMDAsImlhdCI6MCwic3ViIjoxMjU2NDY4NjExfQ.geiaytBjgVIWq-lnDgHStOXIkPE1jIJYsEKDWhYLhy0"
          LESSONS: ${{ inputs.lessons }}
